### ISSUE TITLE
Lights on changes Actnic PWM value

### ISSUE THREAD

**Issue by Smotz** [reefangel/Libraries#185]
When I click "Lights On" on the Android App the ATOpin values are tarnsferred to the PWM values.

Since I am not using the DCPump class for my wavemakers this sets my wavemakers to whatever value the ATOpins are set to.

Not using the dcpump class as I have 2 DC pump wavemakers, and a DC pump return.

for clarification, See post: 
http://forum.reefangel.com/viewtopic.php?f=2&t=4837&p=42361#p42361

**Comment by robertoimai** [comment]
https://github.com/reefangel/Libraries/commit/8a0a3e6e783aebf888a06725cb16c7270fec6ebe
