### ISSUE TITLE
RANet dimming limited to 100 levels of resolution

### ISSUE THREAD

**Issue by cosmith71** [reefangel/Libraries#201]
Current code only allows for transmission of percents (0 -100), which only allows 100 levels of resolution.  The dimming hardware supports 4096 levels of resolution.

Needed is a way to transmit RAW data (12 bits) in the RANet packet.

**Comment by cosmith71** [comment]
Done.  Support added for 2 bytes per dimming channel.

**Comment by robertoimai** [comment]
Can you send me a pull request for this patch?

**Comment by robertoimai** [comment]
cosmith71 fixed this:
https://github.com/reefangel/Libraries/commit/497ee920add5e541bb5db2bd4db295453a6d5fb9
