### ISSUE TITLE
Broken analogWrite function

### ISSUE THREAD

**Issue by robertoimai** [reefangel/Libraries#208]
The commit https://github.com/reefangel/Libraries/commit/8a0a3e6e783aebf888a06725cb16c7270fec6ebe#commitcomment-9530591 broke the analogWrite function

**Comment by lnevo** [comment]
Just curious why is this broken? Wouldn't we want the capability to test and overwride a channel even if using DCPump?

**Comment by robertoimai** [comment]
This is the fix for the patch you mentioned that was broken before.
You can still override, but the channels won't be overriden to memory location when lightson is triggered.
When not using DCPump class, PWM channels get overriden to memory locations automatically when the lightson mode is triggered.

**Comment by lnevo** [comment]
Ok good I can test both of those things then when I attempt it.
