### ISSUE TITLE
Portal Graphs

### ISSUE THREAD

**Issue by lnevo** [reefangel/Libraries#231]
Portal graphs are not showing the extended temperature values. Does it need to be added to the data sent to the portal? or does it need to be updated on the portal side to store those values?

**Comment by robertoimai** [comment]
It needs to be appended to the portal call and the server also needs to be configured.
I'll work on the server later today.

Sincerely,
Roberto Imai

Sent from Galaxy 6 Edge Plus
________________________________

**Comment by lnevo** [comment]
Ok, I’ll try and work on the portal call and the json tonight. I believe you said need to be done as well.
