### ISSUE TITLE
Star Display Issues

### ISSUE THREAD

**Issue by cosmith71** [reefangel/Libraries#233]
Just a couple of question/suggestions.

I have the Star on a simple setup with no expansions other than one relay box.  The PWM expansion still shows up on the screen, though.   It's not critical, but would be nice if only showed when it was installed.

There is also a screen with labels "Exp 0" through "Exp 7" with values of 0.00.  What's that for?

Is there any way to change the names of the ports on the menu and on the uapp?  `ReefAngel.CustomLabels` returns an error saying it's not found.

**Comment by robertoimai** [comment]
Right now, the web wizard doesn't allow to change labels.

You would need to use the Arduino v1.6.8 IDE and the dev branch to be able to change the labels on the RA* screen.

ReefAngel.CustomLabels is present only in the dev branch until we merge it to master.


Sincerely,


Roberto Imai


________________________________
